#!/usr/bin/env bash

# For shellcheck
export status=0

# Happens before every bat file
_common_setup()
{
   # This setup script would be called from the git home directory
   load 'node_modules/bats-support/load.bash'
   load 'node_modules/bats-assert/load.bash'
   # get the containing directory of this file
   # use $BATS_TEST_FILENAME instead of ${BASH_SOURCE[0]} or $0,
   # as those will point to the bats executable's location or the preprocessed file respectively
   PROJECT_ROOT="$( cd "$( dirname "$BATS_TEST_FILENAME" )/.." >/dev/null 2>&1 && pwd )"
   # make executables in src/ visible to PATH
   PATH="$PROJECT_ROOT/src:$PATH"

   cd "$PROJECT_ROOT/test" || exit

   # Remove previous symbolic link tests.
   # Note:  This is called even if skip is used.
   if [ -L "./data" ]; then
      rm ./data
   fi

}

# Happens after every bat file
_common_teardown()
{
   # Remove final symbolic link so its not left around.
   if [ -L "./data" ]; then
      rm ./data
   fi
}

_common_beforeEach()
{
   # define TMPDIR if not already defined 
   if [ -z "${TMPDIR}" ]; then TMPDIR="/tmp"; fi
   if [ ! -d "${TMPDIR}/AA-001" ]; then mkdir "${TMPDIR}/AA-001"; fi
}
