#!/bin/bash
# The above line put there to make shellcheck happy

# This testcase is meant to be the last to shutdown the server
setup()
{
   load './test/setup'
   _common_setup
}

if [ -z "$TMPDIR" ]; then TMPDIR="/tmp"; fi
if [ ! -d "${TMPDIR}/AA-001" ]; then mkdir "${TMPDIR}/AA-001"; fi
touch "${TMPDIR}/AA-001/AirConServer.out"

startServer()
{

   echo  "In startServer" >> "${TMPDIR}"/AA-001/AirConServer.out

   # Start a new AirConServer
   echo "Setup: Starting daemon" >> "${TMPDIR}"/AA-001/AirConServer.out
   node ./AirConServer.js >> "${TMPDIR}/AA-001/AirConServer.out" 2>&1 &
   rc=$?
   if [ "$rc" != 0 ]; then
      echo "Setup: Starting Daemon failed rc: $rc" >> "${TMPDIR}"/AA-001/AirConServer.out
   fi
   sleep 3
   echo "Setup: Daemon shold be started rc: $rc" >> "${TMPDIR}"/AA-001/AirConServer.out

}


@test "AdvAir ( StartServer )" {
   startServer
   rc=$?
   assert_equal "$rc" 0
}
