#!/bin/bash
# The above line put there to make shellcheck happy

# This testcase is meant to be the last to shutdown the server
setup()
{
   load './test/setup'
   _common_setup
}

startServer()
{
   echo  "In startServer" >> /tmp/AA-001/AirConServer.out

   touch /tmp/AA-001/AirConServer.out

   # Start a new AirConServer
   echo "Setup: Starting daemon" >> /tmp/AA-001/AirConServer.out
   node ./AirConServer.js >> /tmp/AA-001/AirConServer.out 2>&1 &
   rc=$?
   if [ "$rc" != 0 ]; then
      echo "Setup: Starting Daemon failed rc: $rc" >> /tmp/AA-001/AirConServer.out
   fi
   sleep 3
   echo "Setup: Daemon shold be started rc: $rc" >> /tmp/AA-001/AirConServer.out

}


@test "AdvAir ( StartServer )" {
   startServer
   rc=$?
   assert_equal "$rc" 0
}
