#!/usr/bin/env bash

startServer()
{
   echo  "In startServer" >> /tmp/AirConServer.out

   touch /tmp/AirConServer.out

   # Start a new AirConServer
   echo "Setup: Starting daemon" >> /tmp/AirConServer.out
   node ./AirConServer.js >> /tmp/AirConServer.out 2>&1 &
   rc=$?
   if [ "$rc" != 0 ]; then
      echo "Setup: Starting Daemon failed rc: $rc" >> /tmp/AirConServer.out
   fi
   sleep 3
   echo "Setup: Daemon shold be started rc: $rc" >> /tmp/AirConServer.out

}
declare -x -f startServer

