#!/usr/bin/env bash

export PORT=2025

stopServer()
{
   rc=0;
   touch /tmp/AirConServer.out
   echo "in stopServer" >> /tmp/AirConServer.out
   # Check if the server is running
   # lsof -Pi :3025 -sTCP:LISTEN
   # local rc=$?
   # if [ "$rc" = "0" ]; then
   if lsof -Pi :$PORT -sTCP:LISTEN -t >/dev/null ; then
      echo "Setup: Stopping daemon" >> /tmp/AirConServer.out
      # Stop it if it is, Just in case its old
      curl -s -g http://localhost:$PORT/quit >> /tmp/AirConServer.out 2>&1
      rc=$?
      if [ "$rc" != 0 ]; then
         echo "Setup: Stopping failed rc: $rc" >> /tmp/AirConServer.out
      fi
      echo "Setup: Curl has Stoped daemon rc: $rc" >> /tmp/AirConServer.out
   fi
}
declare -x -f stopServer
