#!/bin/bash
# The above line put there to make shellcheck happy

# This testcase is meant to be the last to shutdown the server
setup()
{
   load './test/setup'
   _common_setup
}

stopServer()
{
   rc=0;
   touch "${TMPDIR}"/AA-001/AirConServer.out
   echo "in stopServer" >> "${TMPDIR}"/AA-001/AirConServer.out
   # Check if the server is running
   # lsof -Pi :3025 -sTCP:LISTEN
   # local rc=$?
   # if [ "$rc" = "0" ]; then
   if lsof -Pi :"$PORT" -sTCP:LISTEN -t >/dev/null ; then
      echo "Setup: Stopping daemon" >> "${TMPDIR}"/AA-001/AirConServer.out
      # Stop it if it is, Just in case its old
      curl -s -g "http://localhost:$PORT/quit" >> "${TMPDIR}"/AA-001/AirConServer.out 2>&1
      rc=$?
      if [ "$rc" != 0 ]; then
         echo "Setup: Stopping failed rc: $rc" >> "${TMPDIR}"/AA-001/AirConServer.out
      fi
      echo "Setup: Curl has Stoped daemon rc: $rc" >> "${TMPDIR}"/AA-001/AirConServer.out
   fi
}

@test "AdvAir ( StopServer )" {
   stopServer
   rc=$?
   assert_equal "$rc" 0
}
